- hosts: localhost
  connecttion: local
  gather_facts: False
  tasks:
    - name: Import variable file
      include_vars: vars/variables

    - name: Creating VPC for our web Web_stack_vpc
      ec2_vpc_net:
        name: "{{Web_stack_vpc}}"
        cidr_block: "{{VpcCidr}}"
        region: "{{REGION}}"
        dns_support: yes
        dns_hostname: yes
        tenancy: default
        state: present
      register: vpc_out

    - name: Creating Public Subnet1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{REGION}}"
        az: "{{ZONE1}}"
        state: present
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags: 
          Name: WebStack_PubSub1
      register: PubSub1_out
    - name: Creating Public Subnet2 in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{REGION}}"
        az: "{{ZONE2}}"
        state: present
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags: 
          Name: WebStack_PubSub2
      register: PubSub2_out
    - name: Creating Public Subnet3 in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{REGION}}"
        az: "{{ZONE3}}"
        state: present
        cidr: "{{PubSub3Cidr}}"
        map_public: yes
        resource_tags: 
          Name: WebStack_PubSub3
      register: PubSub3_out

    - name: Creating Private Subnet1 in Zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{REGION}}"
        az: "{{ZONE1}}"
        state: present
        cidr: "{{PrivSub1Cidr}}"
        map_public: yes
        resource_tags: 
          Name: WebStack_PrivSub1
      register: PrivSub1_out
    - name: Creating Private Subnet2 in Zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{REGION}}"
        az: "{{ZONE2}}"
        state: present
        cidr: "{{PrivSub2Cidr}}"
        map_public: yes
        resource_tags: 
          Name: WebStack_PrivSub2
      register: PrivSub2_out
    - name: Creating Private Subnet3 in Zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{REGION}}"
        az: "{{ZONE3}}"
        state: present
        cidr: "{{PrivSub3Cidr}}"
        map_public: yes
        resource_tags: 
          Name: WebStack_PrivSub3
      register: PrivSub3_out

    - name: Creating Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{REGION}}"
        state: present
        resource_tags:
          Name: WebStack_IGW
      register: igw_out
      






